# justfile

VERSION := "1.3.0+8"

aab:
  just update-version
  cp .env.prod .env
  flutter clean
  flutter build appbundle --release

update-version:
  # This replaces the version in pubspec.yaml with the VERSION variable
  sed -i '' 's/^version: .*/version: {{VERSION}}/' pubspec.yaml
